apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: product-db
  description: Main product database
  annotations:
    backstage.io/managed-by-location: url:https://github.com/example-org/infrastructure
    backstage.io/techdocs-ref: dir:.
  tags:
    - postgresql
    - database
    - production
spec:
  type: database
  owner: group:database-team
  system: product-system

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: analytics-db
  description: Analytics data warehouse
  annotations:
    backstage.io/managed-by-location: url:https://github.com/example-org/infrastructure
    backstage.io/techdocs-ref: dir:.
  tags:
    - snowflake
    - data-warehouse
    - production
spec:
  type: database
  owner: group:data-team
  system: analytics-system