---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: productsandchannel
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alokkulkarni
  annotations:
    github.com/user-login: alokkulkarni
spec:
  profile:
    displayName: Alok Kulkarni
    email: kulkarni.alok@gmail.com
  memberOf: [platform-team, productsandchannel]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kulkarni.alok
  annotations:
    graph.microsoft.com/user-id: 0cb90d78-b659-4cb1-a8b8-756b6d7f4482
spec:
  profile:
    displayName: Alok Kulkarni
    email: kulkarni.alok@gmail.com
  memberOf:
    - platform-team
    - productsandchannel